name: Build Linux Debian Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:
#   push:
#     paths:
#       - '**.cpp'
#       - '**.h'
#       - '**.o'
#       - '**.sln'
#       - 'makefile'

jobs:
  build_linux:
    name: Build Linux Debian And Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make Linux and Android
      run: |
        ./scripts/build.sh
      # git add .
      # git config --global user.name 'Lateralus138'
      # git config --global user.email 'Lateralus138@users.noreply.github.com'
      # git commit -am "Pushed new project files to master. - $(date)"
      # git push

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        prerelease: False
        artifacts: "./release/debian/strcase.deb,./release/linux/dynamic/strcase,./release/android/static/strcase.android"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.STRCASE_PAT }}
        repository: ${{ github.repository }}
        event-type: trigger-workflow-2
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'