name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:
#   push:
#     paths:
#       - '**.cpp'
#       - '**.h'
#       - '**.o'
#       - '**.sln'
#       - 'makefile'

jobs:
  build_linux:
    name: Build Linux Debian And Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make Linux and Android
      run: |
        ./scripts/build.sh

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Make Windows
      run: |
        & ./scripts/buildwindowsrelease.ps1
