name: Build Windows

on:
  repository_dispatch:
    types: [trigger-workflow-2]

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# on:
#   push:
#     paths:
#       - '**.cpp'
#       - '**.h'
#       - '**.o'
#       - '**.sln'
#       - 'makefile'
jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.sha }}
    - uses: r-lib/actions/setup-r@master
    - uses: r-lib/actions/setup-pandoc@master 
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Make Windows
      run: |
        & ./scripts/buildwindowsrelease.ps1
      # git add .
      # git config --global user.name 'Lateralus138'
      # git config --global user.email 'Lateralus138@users.noreply.github.com'
      # git commit -am "Pushed new project files to master. - $(date)"
      # git push
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        prerelease: False
        artifacts: "./release/windows/strcase-x86.exe,./release/windows/strcase-x64.exe"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.STRCASE_PAT }}
        repository: ${{ github.repository }}
        event-type: trigger-workflow-3
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'