name: Build Windows

on:
  repository_dispatch:
    types: [trigger-workflow-2]

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# on:
#   push:
#     paths:
#       - '**.cpp'
#       - '**.h'
#       - '**.o'
#       - '**.sln'
#       - 'makefile'

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.sha }}
    - uses: microsoft/setup-msbuild@v1.0.2
# - uses: r-lib/actions/setup-r@master
# - uses: r-lib/actions/setup-pandoc@master
    - name: Make Windows
      run: |
        & ./scripts/buildwindowsrelease.ps1
# git pull
# git add .
# git config --global user.name 'Lateralus138'
# git config --global user.email 'Lateralus138@users.noreply.github.com'
# git commit -am "Pushed new project files to master. - $(date)"
# git push
    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.STRCASE_PAT }}
        repository: ${{ github.repository }}
        event-type: trigger-workflow-3
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'