name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:
#   push:
#     paths:
#       - '**.cpp'
#       - '**.h'
#       - '**.o'
#       - '**.sln'
#       - 'makefile'

jobs:
  build_linux:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: |
        if [[ -d "release" ]]; then
          rm -rf release
        fi
        ./scripts/build.sh
        tree
