name: Build MacOas

on:
  repository_dispatch:
    types: [trigger-workflow-3]

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# on:
#   push:
#     paths:
#       - '**.cpp'
#       - '**.h'
#       - '**.o'
#       - '**.sln'
#       - 'makefile'
jobs:
  build_macos:
    name: Build MacOs
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.sha }}
    - uses: r-lib/actions/setup-r@master
    - uses: r-lib/actions/setup-pandoc@master
    - name: Make MacOs
      run: |
        ./scripts/buildmacosrelease.sh
        desktopgen_linux_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "desktopgen MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "linux"\n}'
        if ! [[ -d "./docs/json" ]]; then
          mkdir -p ./docs/json
        fi
        if ! [[ -f "./docs/json/desktopgen_linux_md5.json" ]]; then
          touch ./docs/json/desktopgen_linux_md5.json
        fi
        echo -e "$desktopgen_linux_md5_text" > ./docs/json/desktopgen_linux_md5.json
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5 -r ./release/linux/dynamic/desktopgen | cut -d' ' -f 1)\"/g" docs/json/desktopgen_linux_md5.json
      # git add .
      # git config --global user.name 'Lateralus138'
      # git config --global user.email 'Lateralus138@users.noreply.github.com'
      # git commit -am "Pushed new project files to master. - $(date)"
      # git push
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        prerelease: False
        artifacts: "./release/macos/dynamic/strcase.darwin"
        token: ${{ secrets.GITHUB_TOKEN }}
